name: Server Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'server/**'
      - Makefile

jobs:
  qa-deploy:
    name: "Server (production)"
    uses: kadima-tech/actions/.github/workflows/node-pr.yml@master

    with:
      project: barracuda-dms
      baseDir: server
      postgres: true
      scope: kadima-tech

    secrets:
      token: ${{ secrets.GH_ACCESS_TOKEN }}