name: Frontend Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'web/**'

jobs:
  qa:
    name: "Web (development)"
    uses: kadima-tech/actions/.github/workflows/node-pr.yml@master
    
    with:
      project: barracuda-dms
      baseDir: web
      scope: kadima-tech
    secrets:
      token: ${{ secrets.GH_ACCESS_TOKEN }}
